### ISSUE TITLE
Review pipeline fails on nested Maven multimodule projects

### ISSUE THREAD

**Issue by n-g-work** [epam/edp-tekton#10]
**Describe the bug**

Review pipeline fails for nested Maven multimodule projects.
The same project successfully passes review pipeline in Jenkins.

**To Reproduce**

#### What did you do?

1. In `EDP Headlamp` navigate to `Components` and click `+` to open `Create a new component` form.
2. Click `Application` and `Clone project`.
3. Use [https://github.com/bwgjoseph/maven-nested-multi-module-project.git](https://github.com/bwgjoseph/maven-nested-multi-module-project.git) as the `Repository URL`.
4. Set corresponding values to `Git repo relative path` and `Component name` fields.
5. Click `Java`, then `Java 17`, and then `Maven`.
6. Wait for the application to be processed by EDP
7. Clone the repository, add a minimal `Dockerfile`, commit it and start a review process. 
8. When the pipeline fails for the first time (see "Failure before" error log) add a `<deployable.module>` tag with the value `project` to the parent `pom.xml` and initiate the review process once again.

#### What did you expect to see?

A successful completion of a review pipeline.

#### What did you see instead? Under which circumstances?

At first, the review pipeline fails on the `sonar-prepare-files` Task. Check the attached "Failure before" log file.
Then it fails on the `sonar` Task. Check the attached "Failure after" log files.

**Kubernetes cluster type:**

AWS EKS v1.24

`$ operator-sdk version`

Not applicable.

`$ go version`

Not applicable.

`$ kubectl version`

Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.24.13-eks-0a21954

**Screenshots**

Not applicable.

**Additional context**

Failure before `<deployable.module>` specified: 
[maven-nestef5a827ec027260d0dd80746c973645ecf91d4dec7b2067c9-pod__step-prepare-files__log.txt](https://github.com/epam/edp-tekton/files/11770334/maven-nestef5a827ec027260d0dd80746c973645ecf91d4dec7b2067c9-pod__step-prepare-files__log.txt)

Failure after:
[maven-nested-multi-module-project-main-review-w9vg2-sonar-pod__step-mvn-goals__log.txt](https://github.com/epam/edp-tekton/files/11770342/maven-nested-multi-module-project-main-review-w9vg2-sonar-pod__step-mvn-goals__log.txt)
[maven-neste0955a42c3f5caa8a220e270ec94953d0f3b7849e6a1706f9-pod__step-prepare-files__log.txt](https://github.com/epam/edp-tekton/files/11770341/maven-neste0955a42c3f5caa8a220e270ec94953d0f3b7849e6a1706f9-pod__step-prepare-files__log.txt)

Minimal Dockerfile: [Dockerfile.txt](https://github.com/epam/edp-tekton/files/11770330/Dockerfile.txt)

**Comment by Serg1506** [comment]
Fix available in the EDP release 3.3.0 or higher.
