### ISSUE TITLE
Add java maven support for autotests codebase

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-tekton#11]
Add java-maven support for autotests codebase in QG, which currently support only gradle project. Maven failed on the init stage.

Acceptance Criteria:

- EDP user can onboard and use java maven as autotests;

**Comment by Rolika4** [comment]
We implement java-maven support for autotest as a quality gate.
Now users can use Maven and Gradle build tools to run autotests in cd pipelines to check application quality which will greatly improve post-deploy testing.

<img width="1243" alt="Screenshot 2023-07-03 at 13 01 00" src="https://github.com/epam/edp-tekton/assets/52344283/505ed967-6414-40eb-89e2-7b016d40f5b9">
