### ISSUE TITLE
Make helm-docs as a mandatory step in CI/CD

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-tekton#13]
Create helm-docs template to run from it in order not to be dependent on the helm-docs version.

This line should be absent in the template:
{{ template "helm-docs.versionFooter" . }}

Examples of templates can be found here: https://github.com/norwoodj/helm-docs/blob/master/example-charts/custom-value-notation-type/README.md.gotmpl

**Acceptance criteria:**
- helm-docs is a mandatory step for CI pipelines
- helm-docs templates are added to repos which are used for "create" strategy
- helm-docs are added as a part of Application onboarding process (clone, import strategy)

**Comment by Rolika4** [comment]
We implement step helm-docs that help keep up to dates project docs. This task added to languages:
- Csharp (3.1, 6.0)
- Go (Beego, Gin, OperatorSDK)
- Java (8, 11, 17)
- Js (React, Vue, Angular, Next.js, Express, Antora)
- Python(Python3.8, FastAPI, Flask)

If the repository has some changes that affect readme.md file and you dont update readme.md- review pipeline will fail.

For create strategy file README.MD and README.md.gotmpl are added automatically in the actual state, for clone and import strategies if the repository doesn't exist deploy-templates folder EPD operator creates readme files, if not - the user needs to add these files manually.
