### ISSUE TITLE
Missed cache usage in Antora pipelines

### ISSUE THREAD

**Issue by Rolika4** [epam/edp-tekton#138]
A/C
Add cache to antora pipeline

**Comment by Serg1506** [comment]
![Screenshot_48](https://github.com/epam/edp-tekton/assets/23012062/4d36bece-8947-46a8-b1ea-4a95766ef8fa)
![Screenshot_45](https://github.com/epam/edp-tekton/assets/23012062/1dcc6752-b1f8-4a7b-9682-72d915fb6370)
