### ISSUE TITLE
Multi-module java application fails on docker build step

### ISSUE THREAD

**Issue by SergK** [epam/edp-tekton#141]
**Describe the bug**
The kaniko build process fails for Java multi-module applications due to an incorrect kaniko context. This results in Kaniko being unable to locate the expected artifacts in the `/target` folder. The issue seems to be related to not using `deployable.module` as the mountpoint, which is necessary for kaniko to process the build correctly.

**To Reproduce**

#### What did you do?

- Configured a Java multi-module project for building with kaniko within our CI/CD pipeline.
- Triggered the build process using the existing CI/CD pipeline configuration, which does not specify `deployable.module` as the mountpoint for kaniko.

#### What did you expect to see?

- The kaniko build process was successfully completed.
- Kaniko should have located the necessary artifacts in the `/target` folder for each module, creating the expected container image.

#### What did you see instead? Under which circumstances?

- The Kaniko build process failed with an error indicating that it could not find the expected artifacts in the `/target` folder.
- This issue occurred when using a default kaniko context, without specifying `deployable.module` as the mountpoint.

**Additional context**
- The issue appears to be solvable by configuring the CI/CD pipeline to use `deployable.module` as the mountpoint for kaniko. This would ensure that kaniko has the correct context to find and use the artifacts located in the `/target` folder for Java multi-module applications.

**Comment by Serg1506** [comment]
![Screenshot_55](https://github.com/epam/edp-tekton/assets/23012062/93c8c985-8e71-4afb-8c3b-ce726da01aaa)
