### ISSUE TITLE
Align VCS secret name pattern

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-tekton#27]
Acceptance Criteria:

- secret name - ci-gitlab/github;
- gerrit - without modification;

**Comment by Serg1506** [comment]
![Screenshot_11](https://github.com/epam/edp-tekton/assets/23012062/605ff5cd-5d7a-4ddd-8f90-3f004b424e66)
![Screenshot_12](https://github.com/epam/edp-tekton/assets/23012062/857a0c9a-0a58-4284-b0f9-934e66163ea4)
