### ISSUE TITLE
Migrate content from ct-config configmap to values.yaml

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-tekton#3]
As EDP User, I want to have opportunity to redefine default ct configuration during EDP deploy.

Acceptance Criteria:

- the user can specify сt configs through the values.yaml file when deploying the platform;
- by default values.yaml contains default configs from the EDP team

**Comment by Rolika4** [comment]
Now user can redefine ct-lint configuration during install EDP.
Changes in  [EDP-Tekton](https://github.com/epam/edp-tekton/commit/c083762507b93c695cb1306c9bdb536d5c7c3133), [EDP-Install](https://github.com/epam/edp-install/commit/e582aa7edf858dc536956c5b4c0554c9b4fec021)

To use the custom configuration in ct-lint, redefine the following parameters in the [values.yaml ](https://github.com/epam/edp-install/blob/master/deploy-templates/values.yaml#L322)file:

    edp-tekton:
      ctLint:
        validateMaintainers: ""
        chartSchema: |
          <custom_parameters>
        lintconf: |
          ---
          <custom_parameters>
