### ISSUE TITLE
Failed build pipeline for application helm default versioning type

### ISSUE THREAD

**Issue by Rolika4** [epam/edp-tekton#30]
STR:

Create helm application codebase with default versioning type
Run build pipeline
ER: Build pipeline should be passed

AR: Build pipeline failed with an error

invalid result reference in pipeline task "helm-push": "BUILD_VERSION" is not a named result returned by pipeline task "get-version"

Same issue for Helm Charts library.

**Comment by Serg1506** [comment]
![Screenshot_15](https://github.com/epam/edp-tekton/assets/23012062/379f891e-76a0-4c9a-8488-76d7b39e8072)
