### ISSUE TITLE
Application code review pipeline fails on dockerbuild-verify due to absence of a build step/task

### ISSUE THREAD

**Issue by n-g-work** [epam/edp-tekton#4]
### Describe the bug

Some `Code Review` pipelines do not contain a separate `Build` step, for example:
- gerrit-maven-java11-app-review
- gerrit-maven-java8-app-review
- gerrit-npm-react-app-review

Which causes a failure on the `dockerbuild-verify` step due to the absence of the artifacts to be copied or added with a corresponding instruction in `Dockerfile`.

#### What did you do?

1. Create a sample `JavaScript` / `NPM` project in EDP Headlamp with the `Create` strategy.
2. Clone the Gerrit repository of the new project and change directory into the cloned folder.
3. In the `package.json` file within `scripts` section set `build:clean` command to a more appropriate:
    `npm install && npm cache clean --force && npm ci`.
5. Save the file, stage, commit, and start a code review for the change.

#### What did you expect to see?

A successfully executed `Code Review` pipeline.

#### What did you see instead? Under which circumstances?

Failure on the `dockerbuild-verify` step.

### Versions

EDP: **v3.2.1**
Git Provider: **Gerrit**
Kubernetes: **AWS EKS v1.24.11**

### Screenshots

![image](https://user-images.githubusercontent.com/101364051/234300851-80dfefba-9539-415d-a2f1-fb82482c7ed0.png)

### Additional context
 -

**Comment by NikolayMarusenko** [comment]
Hi @n-g-work!
Thanks for the detailed description of the case, we plan to fix this issue soon.

**Comment by Rolika4** [comment]
Hi @n-g-work!
We have revised the approach and made changes to our review pipelines.
In the NPM framework, the logic has been changed and a build step has been added after the initialization step. A build step has been added to maven pipelines. 
All changes can be seen in the commit [[EPMDEDP-11927]](https://github.com/epam/edp-tekton/commit/9d60bb7d675baedaed0016a78f7f99f8f2f30f0a)
