### ISSUE TITLE
Update tekton-dashboard to LTS

### ISSUE THREAD

**Issue by NikolayMarusenko** [epam/edp-tekton#7]
In current release EDP use 0.35.0 version of Tekton Dashboard.
Available new Tekton Dashboard Releases - https://github.com/tektoncd/dashboard/releases

Acceptance Criteria:

- EDP use latest stable version of Tekton Dashboard

**Comment by alezander86** [comment]
I am happy to report that I successfully completed the task and updated the Tekton Dashboard version in EDP to v0.36.1. EDP now uses the latest stable version of [Tekton Dashboard](https://github.com/tektoncd/dashboard/releases/tag/v0.36.1) at the moment. The update will allow us to take advantage of the new features, improvements, and bug fixes provided in this release. We continue to improve and update our system to provide a more efficient experience.

**Comment by alezander86** [comment]
I am happy to report that I successfully completed the task and updated the Tekton Dashboard version in EDP to v0.36.1. EDP now uses the latest stable version of [Tekton Dashboard](https://github.com/tektoncd/dashboard/releases/tag/v0.36.1) at the moment. The update will allow us to take advantage of the new features, improvements, and bug fixes provided in this release. We continue to improve and update our system to provide a more efficient experience.
