### ISSUE TITLE
Improve semgrep scan task

### ISSUE THREAD

**Issue by SergK** [epam/edp-tekton#79]
We need to:

- disable metrics
- use cache volume
- review existing scanning flags

**Comment by alezander86** [comment]
We can save the cache for this using the command below, but in config automatic creation mode without specialized profiles, the cache is too tiny to save and reuse.

`semgrep --jobs 1 --config=auto . --json --output security-semgrep-report.json --disable-version-check --experimental --registry-caching --ast-caching`
