### ISSUE TITLE
Support POM packaging in build pipelines for Maven libraries

### ISSUE THREAD

**Issue by n-g-work** [epam/edp-tekton#9]
**Is your feature request related to a problem? Please describe.**

Tekton pipelines for Maven library build don't support projects with `<packaging>pom</packaging>`.
Absense of support of the feature causes errors, please check attached logs for details.

**Describe the solution you'd like**

Either treat projects with `<packaging>pom</packaging>` in `pom.xml` as multimodule projects, or add a check for `target/` and `src/test/` folders before preparing them to copy in `prepare-files` step of the `sonar-prepare-files` task.

**Describe alternatives you've considered**

As a workaround it helps to force switching to multimodule build by adding `<deployable.module>pom</deployable.module>` to `<properties/>`. But this can be confusing.

**Additional context**

More information on POM packaging:
https://maven.apache.org/pom.html#aggregation-or-multi-module
https://maven.apache.org/pom.html#inheritance

Logs:
[lb-parent-master-review-p6m9v-sonar-prepare-files-pod__step-prepare-files__log.txt](https://github.com/epam/edp-tekton/files/11733299/lb-parent-master-review-p6m9v-sonar-prepare-files-pod__step-prepare-files__log.txt)

**Comment by Artem-Zahumonnyi** [comment]
Hi,

In the latest version of EDP from the master branch,  the `sonar-prepare-files` Task is removed and instead of this logic, Sonar uses the sonarqube-community-branch-plugin.

We hope this issue will be solved in the upcoming EDP 3.8.0 release.

**Comment by Artem-Zahumonnyi** [comment]
Hi,

After checking, we can confirm that the issue with supporting POM packaging in Maven library build pipelines has been fixed in the EDP 3.8.2 version. This improvement came with the EDP 3.8.0 update. 
If you have any more questions or need help, feel free to ask.
